apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"

  containers:
  - name: nginx
    image: nginx
